apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy: {}
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: __IMAGE__
        name: demo-cicd-k8s-jenkins-front
        env:
        - name: PORT
          value: "80"
        - name: APP_SERVER
          value: "http://back:80"
